### ISSUE TITLE
部署到本地后显示无法加载控制器

### ISSUE THREAD

**Issue by win663** [stephengao666/opentrip#1]
{__NOLAYOUT__}

:(
无法加载控制器:Find
错误位置

FILE: D:\wamp64\www\opentrip-master\ThinkPHP\Library\Think\App.class.php 　LINE: 101
TRACE

#0 D:\wamp64\www\opentrip-master\ThinkPHP\Library\Think\App.class.php(101): E('\xE6\x97\xA0\xE6\xB3\x95\xE5\x8A\xA0\xE8\xBD\xBD\xE6\x8E\xA7...')
#1 D:\wamp64\www\opentrip-master\ThinkPHP\Library\Think\App.class.php(202): Think\App::exec()
#2 D:\wamp64\www\opentrip-master\ThinkPHP\Library\Think\Think.class.php(120): Think\App::run()
#3 D:\wamp64\www\opentrip-master\ThinkPHP\ThinkPHP.php(97): Think\Think::start()
#4 D:\wamp64\www\opentrip-master\index.php(24): require('D:\\wamp64\\www\\o...')
#5 {main}

ThinkPHP3.2.3 { Fast & Simple OOP PHP Framework } -- [ WE CAN DO IT JUST THINK ]

点击首页的其他按钮就是显示无法加载控制器 请问是我操作有误的问题吗？上网百度过，但发现仍无法解决，在这里请问一下各位大神

**Comment by AtomJavaSpring** [comment]
修改连接数据库的相关参数后，从根目录的index.php进去，页面疑似没有CSS，排版布局是乱的，而且页面间的连接也没用。请问该怎么解决。

**Comment by hanzhongzi** [comment]
老板们 你没注意文件夹的权限

**Comment by hanzhongzi** [comment]
> 修改连接数据库的相关参数后，从根目录的index.php进去，页面疑似没有CSS，排版布局是乱的，而且页面间的连接也没用。请问该怎么解决。

老板们 你没注意文件夹的权限
